# Generated by Django 3.2.6 on 2021-08-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='currency',
            field=models.CharField(choices=[('RUR', 'RUR'), ('USD', 'USD'), ('EUR', 'EUR'), ('CZK', 'CZK')], default='RUR', max_length=255),
        ),
    ]
