# Generated by Django 3.2.6 on 2021-08-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0004_auto_20210804_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameLiability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'liability_names',
            },
        ),
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('currency', models.CharField(choices=[('RUR', 'RUR'), ('USD', 'USD'), ('EUR', 'EUR'), ('CZK', 'CZK')], default='RUR', max_length=255)),
                ('date_purchase', models.DateTimeField(auto_now_add=True)),
                ('name', models.ManyToManyField(blank=True, to='finance_app.NameLiability')),
            ],
        ),
    ]
