version: '2.1'

services:

  web:
    tty: true
    image: python:3.9
    depends_on:
      - db
    volumes:
      - .:/opt/finance
    container_name: finance-web
    ports:
      - "0.0.0.0:8040:8000"
    env_file: .env
    working_dir: /opt/finance
    command: /bin/bash -c 'scripts/run_server.sh'

  bot:
    tty: true
    image: python:3.9
    depends_on:
      - web
      - db
    env_file: .env
    volumes:
      - .:/opt/finance
    container_name: finance-bot
    working_dir: /opt/finance
    command: /bin/bash -c 'scripts/run_bot.sh'

  db:
    image: postgres:12.0-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    container_name: finance-db
    env_file: .env

volumes:
    postgres_data:
